parameters:
#    stc_musiczarconia.example.class: Stc\MusiczarconiaBundle\Example
    stc_musiczarconia.repository.scheduler.class: Stc\MusiczarconiaBundle\Repository\SchedulerRepository

services:
#    stc_musiczarconia.example:
#        class: %stc_musiczarconia.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    stc_musiczarconia.repository.scheduler:
        class: %stc_musiczarconia.repository.scheduler.class%
        tags:
            - { name: stc_repository, repository: scheduler }