<?php

namespace Stc\MusiczarconiaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BandRepository extends EntityRepository
{
    public function getBandId($search)
    {
        $res = $this->findBy('%'.$search.'%',null,1);
        if (!empty($res)) {
            return $res['id'];
        }
        return false;
    }

    public function findRelatedShows($bandId)
    {
        $qb = $this->createQueryBuilder('qb')
                   ->select('*')
                   ->from('performances','p')
                   ->where('band_id = '.$bandId)
                   ->getQuery();

    }
}
