Stc\MusiczarconiaBundle\Entity\Scheduler:
    type: entity
    table: scheduler
    indexes:
        IDX_463CEC18A76ED395:
            columns:
                - user_id
        IDX_463CEC18446F285F:
            columns:
                - studio_id
    uniqueConstraints:
        UNIQ_463CEC18A0E239DE:
            columns:
                - confirmation_code
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: string
            nullable: false
            length: 30
            fixed: true
            comment: ''
        reservationTime:
            type: time
            nullable: false
            comment: ''
            column: reservation_time
        duration:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        notes:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        confirmationCode:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: confirmation_code
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
        status:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        user_id:
            type: integer
            nullable: false
        studio_id:
            type: integer
            nullable: false
    manyToMany:
        studios:
            targetEntity: Stc\MusiczarconiaBundle\Entity\Studio
            inversedBy: schedulers
            joinTable:
                name: scheduler_studio
                joinColumns:
                    scheduler_id:
                        referenceColumnName: id
                inverseJoinColumns:
                    studio_id:
                        referenceColumnName: id
        users:
            targetEntity: Stc\UserBundle\Entity\User
            inversedBy: schedulers
            joinTable:
                name: scheduler_user
                joinColumns:
                    scheduler_id:
                        referenceColumnName: id
                inverseJoinColumns:
                    user_id:
                        referenceColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
