Stc\MusiczarconiaBundle\Entity\Studio:
    type: entity
    table: studio
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        code:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        type:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    manyToMany:
        schedulers:
            targetEntity: Stc\MusiczarconiaBundle\Entity\Scheduler
            mappedBy: studios
    lifecycleCallbacks: {  }
