Stc\MusiczarconiaBundle\Entity\Venues:
    type: entity
    table: venues
    id:
        id:
            type: string
            nullable: false
            length: 36
            fixed: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
        dateEntered:
            type: datetime
            nullable: true
            comment: ''
            column: date_entered
        dateModified:
            type: datetime
            nullable: true
            comment: ''
            column: date_modified
        modifiedUserId:
            type: string
            nullable: true
            length: 36
            fixed: true
            comment: ''
            column: modified_user_id
        createdBy:
            type: string
            nullable: true
            length: 36
            fixed: true
            comment: ''
            column: created_by
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        deleted:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
        assignedUserId:
            type: string
            nullable: true
            length: 36
            fixed: true
            comment: ''
            column: assigned_user_id
        venuVenueManagementType:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: venu_venue_management_type
        industry:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        annualRevenue:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: annual_revenue
        phoneFax:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: phone_fax
        billingAddressStreet:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
            column: billing_address_street
        billingAddressCity:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: billing_address_city
        billingAddressState:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: billing_address_state
        billingAddressPostalcode:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
            column: billing_address_postalcode
        billingAddressCountry:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: billing_address_country
        rating:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        phoneOffice:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: phone_office
        phoneAlternate:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: phone_alternate
        website:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        ownership:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        employees:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
        tickerSymbol:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
            column: ticker_symbol
        shippingAddressStreet:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
            column: shipping_address_street
        shippingAddressCity:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: shipping_address_city
        shippingAddressState:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: shipping_address_state
        shippingAddressPostalcode:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
            column: shipping_address_postalcode
        shippingAddressCountry:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: shipping_address_country
        venueType:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            default: bar_tavern
            column: venue_type
        contactIdC:
            type: string
            nullable: true
            length: 36
            fixed: true
            comment: ''
            column: contact_id_c
        capacity:
            type: decimal
            nullable: true
            precision: 18
            scale: 0
            comment: ''
        ageLimit:
            type: decimal
            nullable: true
            precision: 18
            scale: 0
            comment: ''
            column: age_limit
        avgTicketPrice:
            type: decimal
            nullable: true
            precision: 18
            scale: 2
            comment: ''
            column: avg_ticket_price
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, setCreatedByValue ]
        preUpdate: [ setUpdatedAtValue, setModifiedUserId ]