parameters:
#    stc_base.example.class: Stc\BaseBundle\Example

services:
#    stc_base.example:
#        class: %stc_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
