security:

    encoders:
        Stc\Component\Security\Core\User\User:
            algorithm: sha512
        Stc\UserBundle\Entity\User:
            algorithm: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            #id: fos_user.user_manager
            entity: { class: Stc\UserBundle\Entity\User, property: username }


    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                #check_path: fos_user_security_check
                check_path: /login_check
                #login_path: fos_user_security_login
                login_path: /login
                csrf_provider: form.csrf_provider
            logout:
                path: /logout
                target: /
            anonymous: ~
#        admin:
#            pattern: ^/admin
#            form_login:
#                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
#                check_path: login_check
#            logout: true
#            anonymous: false
#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#                check_path: fos_user_security_check
#                login_path: fos_user_security_login
#                csrf_provider: form.csrf_provider
#            logout:       true
#            anonymous:    ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/band_profile/', role: ROLE_USER }
        - { path: ^/venue_profile/', role: ROLE_USER }

