Stc\UserBundle\Entity\Role:
    type: entity
    table: stc_role
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
            length: 30
            fixed: false
        role:
            type: string
            nullable: false
            length: 20
            unique: true
#    manyToOne:
#        band:
#            targetEntity: Stc\MusiczarconiaBundle\Entity\Bands
#            inversedBy: fosusers
#            joinColumn:
#                name: band_id
#                referencedColumnName: id
    manyToMany:
        users:
            targetEntity: Stc\UserBundle\Entity\User
            mappedBy: role